#!/usr/bin/env python3
"""Batch 5: make privacy wording accurate per tool. Each replacement must match exactly once or is reported."""
def rep(f,old,new,count=1):
    s=open(f,encoding="utf-8").read()
    if old not in s: print("MISS",f,old[:70]); return
    open(f,"w",encoding="utf-8").write(s.replace(old,new) if count==0 else s.replace(old,new,count))
if True:
    rep("index.html","No uploads, no accounts — your files stay on your device.","No accounts, and file tools process your audio in your browser instead of uploading it.")
    rep("index.html","Every tool runs locally in your browser. More are being added regularly.","File tools run locally in your browser; Voice to Text is the one exception (see the privacy section). More tools are added regularly.")
    rep("index.html","<p>Your audio file is handled entirely in your browser and never uploaded anywhere.</p>","<p>Audio files you open in the converters, editors and utilities are processed in your browser and are not uploaded to our servers. Voice to Text uses your browser's speech recognition, which may send audio to the browser vendor, and some text-to-speech voices are online voices. Each tool page says which applies.</p>")
    rep("about.html","why your files never leave your device.","why file tools process your audio in your browser.",0)
    rep("about.html","Every tool runs entirely in your browser using the Web Audio API, so your audio file is decoded, edited, and exported without ever being sent anywhere.","Our file-based tools run in your browser using the Web Audio API, so your audio file is decoded, edited, and exported without being sent to a server. The exception is Voice to Text, which uses your browser's speech-recognition service and says so on its own page.")
    rep("about.html","Your audio file is handled entirely in your browser and is never uploaded to our servers.","Audio files you open in the file tools are processed in your browser and are not uploaded to our servers.")
    rep("privacy-policy.html","Every tool on this site processes your audio file locally, inside your own browser, using the Web Audio API. Your file is never uploaded to our servers or to any third party — there is no upload step at all.","The file-based tools (converters, trimmer, merger, compressor, equalizer and similar) process your audio file locally, inside your own browser, using the Web Audio API. Those tools do not upload your file to our servers or to any third party; there is no upload step.")
    rep("privacy-policy.html","<h2>What We Don't Collect</h2>","""<h2>Microphone, Speech and Voice Tools</h2>
<p>The Voice Recorder, Guitar Tuner, BPM Detector and similar tools ask your browser for microphone permission. You can refuse or revoke it in your browser settings; audio from these tools is handled in your browser. <strong>Voice to Text is different:</strong> it uses your browser's built-in speech recognition. In some browsers (Chrome, for example) that feature sends microphone audio to the browser vendor's servers for transcription, under the vendor's own privacy policy. <strong>Text to Speech</strong> uses voices provided by your browser or device; some voices are online voices that may send the text to the browser vendor. Online voices are labeled in the voice list.</p>
<h2>What We Don't Collect</h2>""")
    rep("privacy-policy.html","does not load fonts, ads, or tracking scripts from third-party services.","does not load fonts, ads, or tracking scripts from third-party services. The one third-party resource currently loaded is the open-source lamejs MP3 encoder, served from the jsDelivr CDN on pages that export MP3 files. Loading it means jsDelivr receives the ordinary request details your browser sends (such as your IP address); your audio files are not sent there.")
    rep("text-to-speech.html","That means your text is spoken locally on your device and is never sent to a server to be processed.","Audio Toolkit never receives your text. Note that some browsers include online voices (for example certain Google voices in Chrome) that may send text to the browser vendor to be synthesized. Those voices are marked “online voice” in the voice list, so choose one without that label if you want the text to stay on your device.")
    rep("text-to-speech.html","No. The text is spoken using your device's own speech engine directly in the browser. It is not uploaded or sent anywhere.","Audio Toolkit never receives your text; it is spoken by your browser's speech engine. Some browsers also offer online voices that may send text to the browser vendor. Those are marked “online voice” in the voice list, so pick one without that label to keep the text on your device.",0)
    rep("text-to-speech.html","opt.textContent = v.name + ' (' + v.lang + ')';","opt.textContent = v.name + ' (' + v.lang + ')' + (v.localService === false ? ' – online voice' : '');")
